/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaksi;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macbook
 */
public class KendaraanMasuk extends javax.swing.JFrame {

    /**
     * Creates new form KendaraanMasuk
     */
    public KendaraanMasuk() {
        initComponents();
        setSize(700, 450);
        setLocationRelativeTo(null);
        jTextField2.setEditable(false);
        tampilWaktu();
        loadKendaraan();
        loadTarif();
    }
    
    private String getIdKendaraan(String noPolisi) {

    String idKendaraan = "";

    try {

        Connection conn = koneksi.getConnection();

        String sql = "SELECT id_kendaraan FROM kendaraan WHERE no_polisi=?";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, noPolisi);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            idKendaraan = rs.getString("id_kendaraan");
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Gagal mengambil ID kendaraan : "
                + e.getMessage());
    }

    return idKendaraan;
}
    
    private String getIdTarif(String jenisKendaraan) {

    String idTarif = "";

    try {

        Connection conn = koneksi.getConnection();

        String sql = "SELECT id_tarif FROM tarif WHERE jenis_kendaraan=?";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, jenisKendaraan);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            idTarif = rs.getString("id_tarif");
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Gagal mengambil ID tarif : "
                + e.getMessage());
    }

    return idTarif;
}

    
    public void tampilWaktu() {
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    jTextField2.setText(sdf.format(new Date()));
}
    public void loadKendaraan() {

    try {

        Connection conn = koneksi.getConnection();

        String sql = "SELECT * FROM kendaraan";

        PreparedStatement pst =
                conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        jComboBox1.removeAllItems();

        while (rs.next()) {

            jComboBox1.addItem(
                    rs.getString("no_polisi")
                    + " - "
                    + rs.getString("jenis_kendaraan"));
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Gagal memuat kendaraan");

    }
}
    
    public void loadTarif() {

    try {

        Connection conn = koneksi.getConnection();

        String sql = "SELECT * FROM tarif";

        PreparedStatement pst =
                conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        jComboBox2.removeAllItems();

        while (rs.next()) {

            jComboBox2.addItem(
                    rs.getString("jenis_kendaraan")
                    + " - "
                    + rs.getString("tarif_minimum"));
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Gagal memuat tarif");

    }
}
    
    private void resetForm() {

    if (jComboBox1.getItemCount() > 0) {
        jComboBox1.setSelectedIndex(0);
    }

    if (jComboBox2.getItemCount() > 0) {
        jComboBox2.setSelectedIndex(0);
    }

    tampilWaktu();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kendaraan Masuk");

        jLabel2.setText("Kendaraan");

        jLabel3.setText("Tarif");

        jLabel4.setText("Waktu Masuk");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2, 0, 225, Short.MAX_VALUE))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1)))
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {

    if (jComboBox1.getSelectedItem() == null
            || jComboBox2.getSelectedItem() == null) {

        JOptionPane.showMessageDialog(
                null,
                "Data kendaraan dan tarif harus dipilih");

        return;
    }

    String dataKendaraan =
            jComboBox1.getSelectedItem().toString();

    String dataTarif =
            jComboBox2.getSelectedItem().toString();

    String noPolisi =
            dataKendaraan.split(" - ")[0];

    String jenisKendaraan =
            dataTarif.split(" - ")[0];

    String idKendaraan =
            getIdKendaraan(noPolisi);

    String idTarif =
            getIdTarif(jenisKendaraan);

    if (idKendaraan.equals("") || idTarif.equals("")) {

        JOptionPane.showMessageDialog(
                null,
                "ID kendaraan atau ID tarif tidak ditemukan");

        return;
    }

    Connection conn =
            koneksi.getConnection();

    String cekSql =
            "SELECT * FROM transaksi "
            + "WHERE id_kendaraan=? AND status='Masuk'";

    PreparedStatement pstCek =
            conn.prepareStatement(cekSql);

    pstCek.setString(1, idKendaraan);

    ResultSet rs =
            pstCek.executeQuery();

    if (rs.next()) {

        JOptionPane.showMessageDialog(
                null,
                "Kendaraan ini masih tercatat sedang parkir");

        return;
    }

    String sql =
            "INSERT INTO transaksi "
            + "(id_kendaraan, id_tarif, waktu_masuk, total_tarif, status) "
            + "VALUES (?, ?, ?, ?, ?)";

    PreparedStatement pst =
            conn.prepareStatement(sql);

    pst.setString(1, idKendaraan);
    pst.setString(2, idTarif);
    pst.setString(3, jTextField2.getText());
    pst.setInt(4, 0);
    pst.setString(5, "Parkir");

    pst.executeUpdate();

    JOptionPane.showMessageDialog(
            null,
            "Data kendaraan masuk berhasil disimpan");

    resetForm();

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            null,
            "Data gagal disimpan : "
            + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
resetForm();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
helper.Navigasi.kembaliKeDashboard(this);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KendaraanMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KendaraanMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KendaraanMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KendaraanMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KendaraanMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
